spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
  jpa:
    show-sql: false

app:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}

