spring:
  application:
    name: room-reservation
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

server:
  port: 8080

app:
  upload:
    logo-cleanup:
      enabled: ${LOGO_CLEANUP_ENABLED:true}
      cron: ${LOGO_CLEANUP_CRON:0 0 4 * * *}
      zone: ${LOGO_CLEANUP_ZONE:Asia/Seoul}
